# Generated by Django 3.1.6 on 2022-08-13 16:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import photography.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('hashtags', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='TravelDiary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('title', models.CharField(max_length=150)),
                ('style_formats', models.TextField()),
                ('content', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photography.album')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('feature', models.BooleanField(default=False)),
                ('posted_on', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('hashtags', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(upload_to=photography.models.rename_image)),
                ('thumbnail', models.ImageField(editable=False, upload_to=photography.models.rename_thumbnail)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photography.album')),
                ('genre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='photography.genre')),
            ],
        ),
    ]
