# Generated by Django 4.1.7 on 2023-05-08 12:39

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import photography.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('hashtags', models.CharField(blank=True, max_length=200, null=True)),
                ('travel_date', models.DateField(default=django.utils.timezone.now)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-travel_date'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='LandingImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=photography.models.rename_image)),
                ('active', models.BooleanField(default=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('thumbnail', models.ImageField(editable=False, upload_to=photography.models.rename_thumbnail)),
            ],
        ),
        migrations.CreateModel(
            name='ProfilePhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=photography.models.rename_image)),
                ('active', models.BooleanField(default=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('thumbnail', models.ImageField(editable=False, upload_to=photography.models.rename_thumbnail)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('title', models.CharField(max_length=150)),
                ('summary', models.TextField(null=True)),
                ('author', models.CharField(max_length=150)),
                ('travel_date', models.DateField(default=django.utils.timezone.now)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to=photography.models.rename_image)),
                ('thumbnail', models.ImageField(blank=True, editable=False, null=True, upload_to=photography.models.rename_thumbnail)),
            ],
        ),
        migrations.CreateModel(
            name='TravelDiary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('title', models.CharField(max_length=150)),
                ('summary', models.TextField(null=True)),
                ('author', models.CharField(max_length=150)),
                ('travel_date', models.DateField(default=django.utils.timezone.now)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to=photography.models.rename_image)),
                ('thumbnail', models.ImageField(blank=True, editable=False, null=True, upload_to=photography.models.rename_thumbnail)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('feature', models.BooleanField(default=False)),
                ('posted_on', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('hashtags', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(upload_to=photography.models.rename_image)),
                ('thumbnail', models.ImageField(editable=False, upload_to=photography.models.rename_thumbnail)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photography.album')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photography.genre')),
            ],
        ),
    ]
