# Generated by Django 3.1.6 on 2021-11-27 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('hashtags', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BasicInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('feature', models.BooleanField(default=False)),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
                ('image_path', models.ImageField(upload_to='images/')),
                ('tags', models.CharField(max_length=100)),
                ('image_thumbnail_path', models.ImageField(editable=False, upload_to='images/thumbnails/')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photography.album')),
            ],
        ),
    ]
