# Generated by Django 4.1.7 on 2023-05-09 08:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import photography.models


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Panorama',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('feature', models.BooleanField(default=False)),
                ('posted_on', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('hashtags', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(upload_to=photography.models.rename_image)),
                ('thumbnail', models.ImageField(editable=False, upload_to=photography.models.rename_thumbnail)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photography.album')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photography.genre')),
            ],
        ),
    ]
