# Generated by Django 4.1.7 on 2023-05-14 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0003_traveldiary_publish_delete_panorama'),
    ]

    operations = [
        migrations.AddField(
            model_name='traveldiary',
            name='meta_keywords',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
