# Generated by Django 4.1.7 on 2024-01-30 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0004_traveldiary_meta_keywords'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='travel_date',
            new_name='publish_date',
        ),
        migrations.AddField(
            model_name='project',
            name='project_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='source_code_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
